name: Testing!

on:
  [push]


jobs:
  test-ci-pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18.2'
      - run: npm install .
      - run: npm run test

